### ISSUE TITLE
Error encountered while loading 

### ISSUE THREAD

**Issue by hafez-ahmad** [JuliaStats/RDatasets.jl#97] opened 2020-06-02 06:48 UTC
dataset("datasets","iris")
Error encountered while loading "C:\\Users\\hafez\\.julia\\packages\\RDatasets\\WIQKI\\src\\..\\data\\datasets\\iris.rda".

Fatal error:
ERROR: UndefVarError: identifier not defined
Stacktrace:
 [1] handle_error(::UndefVarError, ::FileIO.File{FileIO.DataFormat{:RData}}) at C:\Users\hafez\.julia\packages\FileIO\ZknoK\src\error_handling.jl:82
 [2] handle_exceptions(::Array{Any,1}, ::String) at C:\Users\hafez\.julia\packages\FileIO\ZknoK\src\error_handling.jl:77
 [3] load(::FileIO.Formatted; options::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\hafez\.julia\packages\FileIO\ZknoK\src\loadsave.jl:186
 [4] load at C:\Users\hafez\.julia\packages\FileIO\ZknoK\src\loadsave.jl:166 [inlined]
 [5] #load#13 at C:\Users\hafez\.julia\packages\FileIO\ZknoK\src\loadsave.jl:118 [inlined]
 [6] load at C:\Users\hafez\.julia\packages\FileIO\ZknoK\src\loadsave.jl:118 [inlined]
 [7] dataset(::String, ::String) at C:\Users\hafez\.julia\packages\RDatasets\WIQKI\src\dataset.jl:12
 [8] top-level scope at none:0

**Comment by bkamins** [comment] 2020-06-13 16:53
This is fixed by RData.jl master that is not released yet. I will try to ask maintainers to make appropriate releases for RData.jl and RDatasets.jl.

**Comment by bkamins** [comment] 2020-06-14 06:11
@hafez-ahmad and @liwen-alt - can you please report what are the versions of:
* RData.jl
* RDatasets.jl
* DataFrames.jl
installed on your machine?

(in general just updating packages should resolve this issue)

**Comment by liwen-alt** [comment] 2020-06-15 02:58
![image](https://user-images.githubusercontent.com/63285313/84613914-1a52a380-aef7-11ea-85e4-9b5859f45903.png)

**Comment by liwen-alt** [comment] 2020-06-15 03:27
I have the same problem,This is the version of my package

**Comment by bkamins** [comment] 2020-06-15 08:48
You are not working on latest releases of the packages. Your version of DataFrames.jl is 0.20.2 and it still has `identifer` function defined in deprecated code, so it is strange you get this exact error.

The easiest fix is to update your packages:
* DataFrames.jl to 0.21.2 release
* RData to 0.7.2 release

Please let me know if this helped (it works on my computer).

**Comment by liwen-alt** [comment] 2020-06-15 10:26
I have updated package,but the version of package hasn't changed.
![image](https://user-images.githubusercontent.com/63285313/84647064-83f1a280-af35-11ea-8796-16775a6f5490.png)
![image](https://user-images.githubusercontent.com/63285313/84647148-a2579e00-af35-11ea-9335-4cdc648a7e87.png)
![image](https://user-images.githubusercontent.com/63285313/84647217-b7343180-af35-11ea-8b92-4ca95bb34c15.png)

**Comment by bkamins** [comment] 2020-06-15 11:27
The problem is that you are probably using default Project.toml for all your projects. This is not a recommended practice. However, if you want to use it then you can follow what I have described [here](https://bkamins.github.io/julialang/2020/05/11/package-version-restrictions.html) to understand which package is causing problems with update.

(start with `add DataFrames@0.21.2` and see what you get in the error message)

I have also noticed that you use outdated versions of CSV.jl and DataFramesMeta.jl (maybe also others, but for these I can quickly tell that you have them in wrong versions).

When you identify what package stops DataFrames.jl and RData.jl from being updated please let me know, as probably its maintainers should get notified about it. Thank you!

**Comment by liwen-alt** [comment] 2020-06-15 12:22
Thank you ! 

现在这个问题解决了
Now the problem is solved

**Comment by liwen-alt** [comment] 2020-06-15 12:22
Thank you!
Now the problem is solved.

**Comment by bkamins** [comment] 2020-06-15 12:45
Great, so I think the issue can be closed by someone from JuliaStats.jl.

**Comment by asinghvi17** [comment] 2020-06-15 12:47
@bkamins should we create a new release with more restrictive compat?

**Closed** 2020-06-15 12:47 UTC

**Comment by bkamins** [comment] 2020-06-15 13:04
It should be not strictly required, as RData.jl has a more restrictive compat and package manager should resolve it properly (as constraints in RDatasets.jl are not binding anyway).

However, in some cases (especially if someone uses default Project.toml/Manifest.toml which are typically quite polluted) actually using Package Manager is not as obvious as it seems (it does the right job, but you need to know more than just `add PackageName` to control things properly).

Therefore, the cleanest thing would be:
1. have a new version of RDatatests.jl with more restrictive version requirements
2. retroactively make version requirements for RDatasets.jl for past releases more restrictive in GlobalRegistry (as now they are flexible, so things potentially can get messy anyway)

But I think that the reported problem is only transitory, so things can be left as is.
